##  1.a (5%) Find the eigenvalues and a basis consisting of eigenvectors of 


$$A = \begin{bmatrix}
    1  & 1 & -1  \\
    -3  & -3 & 1  \\
    -3  & -3 & 1  \\
\end{bmatrix}$$

##  1.b (5%) Find the coordinates of the vector with respect to the basis of eigenvectors found at problem 1.

$$v = \begin{bmatrix}
     0  \\
     1  \\
     0  \\
\end{bmatrix}$$

## 1.c (5%) Calculate  $A^{2019}v$

In [14]:
import numpy as np

a = np.matrix([[1, 1, -1], [-3, -3, 1], [-3, -3, 1]])
v = np.matrix([[0,1,0]])
pow = (np.abs(a) ** 2019) * np.sign(a)
np.multiply(pow,v)

matrix([[                   0, -4771718345474059377,
                            0],
        [                   0,  4571248787882505707,
                            0],
        [                   0,  4571248787882505707,
                            0]])

## 2. (10%) A typical page in a book contains one typo per page.  What is the probability that there are exactly 8 typos in a given 10-page chapter?

This is a Poisson distribution. Since the expected number of typos on one page is 1, the expected number of typos in 10 pages is 10. Hence, we use the Poisson formula with λ = 10

## 3. (10%) Suppose  that  every  page  in  the  chapter  contains  exactly  3000  characters,  and there is still an average of one typo per page.  What is the probability that there are exactly 8 typos in the 10-page chapter?

This time, we use a binomial distribution, where a typo counts as a success. The probability of success is 1 ; we have 30000 trials

## 4.(10%) Draw an ANN to implment $A \bigoplus B$

First, we create the network with random weights and random biases. Second, we set the activation of the two input nodes from the columns 'a' and 'b' in the table, and run the network forward. Third, we compare the output produced by the network to the desired output (in the third column of the truth table), and calculate the difference between the actual output and the desired output. This difference is the error signal. Fourth, we change the weights of the connections that connect to the output node, and the bias of the output node. Fifth, we pass the error back to the hidden layer, and change the biases and weights of those connections. Then the cycle repeats with new inputs and new outputs. The network trains until the average error (calculated over all four rows in the truth table) approaches zero.

## 5. (20%) Train a deep MLP on the MNIST dataset and see if how much accuracy you can ge?


## 6. (20%) For MNIST, can you design a new model based on CNN to retrain? How much accuracy get now? If you have GPU, try to play with those model paramters.

## 7. (15%) Given iris.csv data set. Using NN with Cross-Validation to Classify. Report Accuracy.

In [5]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import svm

iris = datasets.load_iris()
iris.data.shape, iris.target.shape

((150, 4), (150,))

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    iris.data, iris.target, test_size=0.4, random_state=0)

X_train.shape, y_train.shape

X_test.shape, y_test.shape


clf = svm.SVC(kernel='linear', C=1).fit(X_train, y_train)
clf.score(X_test, y_test)       

0.9666666666666667

In [7]:
from sklearn.model_selection import cross_val_score
clf = svm.SVC(kernel='linear', C=1)
scores = cross_val_score(clf, iris.data, iris.target, cv=5)
scores     

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [8]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))


Accuracy: 0.98 (+/- 0.03)


In [9]:
from sklearn import metrics
scores = cross_val_score(
    clf, iris.data, iris.target, cv=5, scoring='f1_macro')
scores   

array([0.96658312, 1.        , 0.96658312, 0.96658312, 1.        ])

In [10]:
from sklearn.model_selection import ShuffleSplit
n_samples = iris.data.shape[0]
cv = ShuffleSplit(n_splits=5, test_size=0.3, random_state=0)
cross_val_score(clf, iris.data, iris.target, cv=cv)  

array([0.97777778, 0.97777778, 1.        , 0.95555556, 1.        ])

In [11]:
def custom_cv_2folds(X):
    n = X.shape[0]
    i = 1
    while i <= 2:
        idx = np.arange(n * (i - 1) / 2, n * i / 2, dtype=int)
        yield idx, idx
        i += 1

custom_cv = custom_cv_2folds(iris.data)
cross_val_score(clf, iris.data, iris.target, cv=custom_cv)

array([1.        , 0.97333333])

In [12]:
from sklearn import preprocessing
X_train, X_test, y_train, y_test = train_test_split(
    iris.data, iris.target, test_size=0.4, random_state=0)
scaler = preprocessing.StandardScaler().fit(X_train)
X_train_transformed = scaler.transform(X_train)
clf = svm.SVC(C=1).fit(X_train_transformed, y_train)
X_test_transformed = scaler.transform(X_test)
clf.score(X_test_transformed, y_test)  

0.9333333333333333

In [13]:
from sklearn.pipeline import make_pipeline
clf = make_pipeline(preprocessing.StandardScaler(), svm.SVC(C=1))
cross_val_score(clf, iris.data, iris.target, cv=cv)

array([0.97777778, 0.93333333, 0.95555556, 0.93333333, 0.97777778])

In [14]:
from sklearn.model_selection import cross_validate
from sklearn.metrics import recall_score
scoring = ['precision_macro', 'recall_macro']
clf = svm.SVC(kernel='linear', C=1, random_state=0)
scores = cross_validate(clf, iris.data, iris.target, scoring=scoring,
                        cv=5, return_train_score=False)
sorted(scores.keys())

scores['test_recall_macro']     

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [15]:
scores = cross_validate(clf, iris.data, iris.target,
                        scoring='precision_macro', cv=5,
                        return_estimator=True)
sorted(scores.keys())


['estimator', 'fit_time', 'score_time', 'test_score', 'train_score']